### ISSUE TITLE
由于at的CQ码增加了name字段导致群里被at的bot上报的to_me字段恒为false

### ISSUE THREAD

**Issue by desolution025** [Jigsaw111/nonebot-adapter-gocq#2]
gocq版本: 2.0.0a13

由于上报的at消息里没有name字段，导致判断是否to_me时判断at_me_seg的MessageSegment不等
![image](https://user-images.githubusercontent.com/69784210/117484533-c4b53880-af99-11eb-97d0-ac807fe49fbe.png)

使用这个测试了一下并不能判断为to_me
```
@tst_tome.handle()
async def tomeornot(bot: Bot, event: GroupMessageEvent):
    logger.debug(f'tome : {event.to_me}')
```
![image](https://user-images.githubusercontent.com/69784210/117485233-b74c7e00-af9a-11eb-9461-334972732844.png)

建议MessageSegment.at函数传入name为None时返回消息段里直接不含name

**Comment by Jigsaw111** [comment]
感谢使用！

我将在下一个版本更新之前重写 event 的大部分方法，同时也会解决此问题。

当然，gocq adapter 的版本号是跟 cqhttp adapter 同步的，所以您可能要自己 clone 后 build。
